name: Run Pytest on Pull Request

on:
  pull_request:
    branches:
      - main  # Adjust to your default branch if different (e.g., 'master')

jobs:
  test:
    runs-on: ubuntu-latest  # You can use other OS runners like 'windows-latest' or 'macos-latest'

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Choose your desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt with pytest

    # Step 4: Run Pytest
    - name: Run Pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Customize pytest options if needed
